export const siteConfig = {
  name: "Telvis",
  url: "https://telvis.uk",
  primaryKeyword: "IPTV UK",
  title:
    "IPTV UK – Premium IPTV Subscription UK | 20,000+ Channels & Free Trial",
  description:
    "Access IPTV UK with 20,000+ live channels, sports, movies and series. Free trial available, instant activation, guided setup and 24/7 support.",
  h1: "IPTV UK – Premium IPTV Subscription from £9.99 with Free 24-Hour Trial",
} as const;

export const routes = {
  home: "/",
  trial: "/free-trial",
  plans: "/#plans",
  installation: "/installation-guide",
  reviews: "/reviews",
  contact: "/contact",
  refund: "/refund-policy",
} as const;

export const supportConfig = {
  email: "support@telvis.uk",
  whatsapp: "+44 7482 794475",
  whatsappUrl: "https://wa.me/447482794475",
  downloaderCode: "TELVIS",
} as const;

/** Optimized brand assets served from /public (generated by scripts/generate-brand-icons.mjs). */
export const brandAssets = {
  logo512: "/logo-512.png",
  ogImage: "/og-image.png",
  favicon48: "/favicon-48.png",
  appleTouchIcon: "/apple-touch-icon.png",
  manifest: "/site.webmanifest",
} as const;

export const navLinks = [
  { href: routes.home, label: "Home" },
  { href: routes.installation, label: "Installation Guide" },
  { href: routes.reviews, label: "Reviews" },
  { href: routes.contact, label: "Contact Us" },
] as const;

export const footerQuickLinks = [
  { href: routes.plans, label: "View Plans" },
  { href: routes.trial, label: "Start Free Trial" },
  { href: "/#faq", label: "FAQ" },
] as const;

export const footerLegalLinks = [
  { href: routes.refund, label: "Refund Policy" },
] as const;
